/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
  return {
	  Shader: (() => {
	    return defineComponent(
	      world,
	      { owner: RecsType.BigInt, color: { color_one: { a: RecsType.Number, b: RecsType.Number, c: RecsType.Number }, color_two: { a: RecsType.Number, b: RecsType.Number, c: RecsType.Number }, condition: RecsType.Number } },
	      {
	        metadata: {
	          name: "Shader",
	          types: ["felt252","u8","u8","u8","u8","u8","u8","u8"],
	          customTypes: ["Mix","Vec3","Vec3"],
	        },
	      }
	    );
	  })(),
  };
}
